apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- route.yaml
commonLabels:
  app: andres-mareca-my-nextjs-app
  app.kubernetes.io/instance: andres-mareca-my-nextjs-app-instance
  app.kubernetes.io/name: andres-mareca-my-nextjs-app
images:
- name: quay.io/upslopeio/express-app
  newName: quay.io/supersonido/nextjs-app
  newTag: 3adec74bfb9b5dea9c45d987fb7f42586675427c
